#ifndef __NIZFC_CONFIG_H__
#define __NIZFC_CONFIG_H__

#define MAIN_TASK_PRIORITY	0
#define RECEIVER_TASK_PRIORITY	1
#define SERIAL_TASK_PRIORITY	2
#define LEDS_TASK_PRIORITY	3

#endif /* __NIZFC_CONFIG_H__ */
